ALTER TABLE leads ADD COLUMN IF NOT EXISTS qualification text NOT NULL DEFAULT 'unreviewed'
  CHECK (qualification IN ('unreviewed', 'target', 'non_target'));
ALTER TABLE leads ADD COLUMN IF NOT EXISTS consultation_status text NOT NULL DEFAULT 'unreviewed'
  CHECK (consultation_status IN ('unreviewed', 'held', 'not_held'));
ALTER TABLE leads ADD COLUMN IF NOT EXISTS contract_status text NOT NULL DEFAULT 'unreviewed'
  CHECK (contract_status IN ('unreviewed', 'signed', 'not_signed'));
ALTER TABLE leads ADD COLUMN IF NOT EXISTS revenue_rub numeric(12, 2) NOT NULL DEFAULT 0
  CHECK (revenue_rub >= 0);

CREATE TABLE IF NOT EXISTS marketing_costs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  week_start date NOT NULL,
  channel text NOT NULL CHECK (channel <> ''),
  spend_rub numeric(12, 2) NOT NULL CHECK (spend_rub >= 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (week_start, channel)
);

CREATE INDEX IF NOT EXISTS marketing_costs_week_idx ON marketing_costs (week_start DESC, channel);
CREATE INDEX IF NOT EXISTS leads_economics_idx ON leads (created_at, qualification, contract_status);
